[package]
id = gantt_viz_for_dashboard_studio

[id]
version = 0.1.0
name = gantt_viz_for_dashboard_studio

[ui]
is_visible = 1
label = Gantt Viz For Dashboard Studio
show_in_nav = 0

[launcher]
author = Daniel Spavin
description = A Gantt chart for use in Dashboard Studio
version = 0.1.0

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
